services:
  DUMB:
    container_name: DUMB
    image: iampuid0/dumb:dev
    stop_grace_period: 30s
    shm_size: 128mb
    stdin_open: true
    tty: true
    volumes:
      - /home/username/docker/DUMB/config:/config
      - /home/username/docker/DUMB/log:/log
      - /home/username/docker/DUMB/data:/data
      - /home/username/docker/DUMB/mnt/debrid:/mnt/debrid
    environment:
      - TZ=
      - PUID=
      - PGID=
    ports:
      - "3005:3005"                                                  ## DUMB Frontend
      - "3000:3000"                                                  ## NZBDav Frontend
      - "8080:8080"                                                  ## NZBDav Backend
      - "8282:8282"                                                  ## Decypharr 
      - "8096:8096"                                                  ## Jellyfin/Emby
      - "9696:9696"                                                  ## Prowlarr 
      - "8989:8989"                                                  ## Usenet Sonarr HD
      - "8990:8990"                                                  ## Debrid Sonarr HD
      - "8991:8991"                                                  ## Usenet Sonarr 4K
      - "8992:8992"                                                  ## Debrid Sonarr 4K 
      - "7878:7878"                                                  ## Usenet Radarr HD
      - "7879:7879"                                                  ## Debrid Radarr HD
      - "7880:7880"                                                  ## Usenet Radarr 4k
      - "7881:7881"                                                  ## Debrid Radarr 4K
      - "6969:6969"                                                  ## XXX
      - "5055:5055"                                                  ## Seerr 
      - "6868:6868"                                                  ## Profilarr
    devices:
      - /dev/fuse:/dev/fuse:rwm
      - /dev/dri:/dev/dri
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined